version: '3'
volumes:
  dados:
networks:
  database:
  web:
  queues:
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      # Volume dos Dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database
  frontend: 
    image: nginx:1.13
    volumes: 
      # Site de Entrada
      - ./web:/usr/share/nginx/html/
      # Configuração do Volume do Proxy Reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      # Aplicação APP
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - database
      - web
      - queues
    depends_on: 
      - db
  queue:
    image: redis:3.2
    networks:
      - queues
  worker:
    image: python:3.6
    volumes:
      # Mapeamento do Caminho do Worker
      - ./worker:/worker
    working_dir: /worker
    command: bash ./app.sh
    networks:
      - queues
    depends_on: 
      - queue

